version: '3.8'

services:
  # SERVER
  server:
    build:
      context: .
    container_name: server
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      # SERVER_NAME: ${SERVER_NAME}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - 99tech
  # POSTGRESQL
  postgresql:
    image: postgres:16-alpine
    command: postgres -c 'max_connections=50'
    restart: always
    container_name: postgres99tech
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - 99tech

volumes:
  systemCluster:

networks:
  99tech:
    name: 99tech